title: Esteeb.com
email: steve@esteeb.com
description: >- # this means to ignore newlines until "baseurl:"
  Information for my Sunday School class, and friends of the church.
baseurl: ""
url: "ElEsteeb.github.io"
collections:
  devotionals:
    output: true
  notes:
    output: true
  class_recordings:
    output: true
