title: Esteeb.com
description: Information for my Sunday School class, and friends of the church.
permalink: /:categories/:year-:month-:day-:title # Ensure this works well for both languages within their folders
url: "https://www.esteeb.com"  # Your custom domain
baseurl: ""                    # Empty since your site is at the root of the domain

# Google Analytics
google_analytics: G-Y0QLNLWWLX

collections:
  devotionals:
    output: true
    permalink: /devotionals/:name/ # Example permalink for collection items
  notes:
    output: true
    permalink: /notes/:name/
  class_recordings:
    output: true
    permalink: /class_recordings/:name/

# Default layouts for collections
defaults:
  # Set default language for all pages (HTML, Markdown) to English
  - scope:
      path: "" # Applies to all files in the root and subdirectories
      type: "pages" # Specifically targets HTML/Markdown files that are not collections
    values:
      lang: "en" # Automatically set lang: en

  # Your existing default for 'notes' collection (keep this)
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "essay"
  - scope:
      path: ""
      type: "devotionals"
    values:
      lang: "en"
  - scope:
      path: ""
      type: "notes"
    values:
      lang: "en"
  - scope:
      path: ""
      type: "class_recordings"
    values:
      lang: "en"

plugins:
  - jekyll-seo-tag
  - jekyll-polyglot # CORRECTED: Removed the extra colon here!

languages: ["en", "es"] # Your supported languages
default_lang: "en"     # Your existing site's language (English in this case)
lang_from_path: true 
exclude_from_localization:
  - "assets"
  - "_data"
  - "images"
  - "_includes"
  - "_layouts"
  - "CNAME"
  - "robots.txt"
  - "styles.css" # Assuming it's a static file directly in root, otherwise your 'assets' exclusion should cover it.
  - "search-index.json"
  - "old-styles.css" # Only if you still want to serve it, otherwise remove it from repo
  # Gemfile.lock and Gemfile do not need to be excluded as they are not processed by Jekyll for content.