title: Esteeb.com
description: Information for my Sunday School class, and friends of the church.
permalink: /:categories/:year-:month-:day-:title
url: "https://www.esteeb.com"  # Your custom domain
baseurl: ""                    # Empty since your site is at the root of the domain

# Google Analytics
google_analytics: G-Y0QLNLWWLX
collections:
  devotionals:
    output: true
    permalink: /devotional/:name
  notes:
    output: true
    permalink: /notes/:name
  class_recordings:
    output: true
    permalink: /recordings/:name

# Default layouts for collections
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "essay"

plugins:
  - jekyll-seo-tag
