title: Esteeb.com
email: steve@esteeb.com
description: >- # this means to ignore newlines until "baseurl:"
  Information for my Sunday School class, and friends of the church.
baseurl: ""
url: "https://www.esteeb.com"  # Your custom domain

# Google Analytics
google_analytics: G-Y0QLNLWWLX
collections:
  devotionals:
    output: true
    permalink: /devotional/:name
  notes:
    output: true
    permalink: /notes/:name
  class_recordings:
    output: true
    permalink: /recordings/:name

# Default layouts for collections
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "essay"
