name: Scheduled Jekyll Rebuild

on:
  schedule:
    # Runs at 6:00 AM CST (12:00 UTC)
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trigger_rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make empty commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Trigger rebuild for scheduled post"
          git push
