name: pages-build-deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write  # Add this line to give the GITHUB_TOKEN the required permission

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Add any other build steps here

      - name: Deploy to GitHub Pages
        id: pages
        uses: actions/deploy-pages@v1
        with:
          timeout: '600'  # Increase the timeout duration to 10 minutes
